global:
  scrape_interval: 15s  # How frequently to scrape targets
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'wordpress'
    static_configs:
      - targets: ['wordpress:9000']
